// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using ErsatzTV.Core.Next.Config;
//
//    var channelConfig = ChannelConfig.FromJson(jsonString);
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8602
#pragma warning disable CS8603

namespace ErsatzTV.Core.Next.Config
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class ChannelConfig
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("fallback")]
        public Fallback? Fallback { get; set; }

        [JsonPropertyName("ffmpeg")]
        public Ffmpeg Ffmpeg { get; set; }

        [JsonPropertyName("normalization")]
        public Normalization Normalization { get; set; }

        [JsonPropertyName("playout")]
        public Playout Playout { get; set; }

        /// <summary>
        /// Schema version URI, e.g. "https://ersatztv.org/channel/version/0.1.0". Missing means
        /// 0.0.0.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("version")]
        public string? Version { get; set; }
    }

    /// <summary>
    /// Controls the content that replaces scheduled content when there is nothing to play
    /// (a gap in the playout) or when the scheduled item fails
    /// </summary>
    public partial class Fallback
    {
        /// <summary>
        /// Burn the reason for the fallback into the fallback video; this is always burned,
        /// regardless of the normalization subtitle mode
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("show_error")]
        public bool? ShowError { get; set; }
    }

    public partial class Ffmpeg
    {
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("disabled_filters")]
        public List<string>? DisabledFilters { get; set; }

        [JsonPropertyName("ffmpeg_path")]
        public string? FfmpegPath { get; set; }

        [JsonPropertyName("ffprobe_path")]
        public string? FfprobePath { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("preferred_filters")]
        public List<string>? PreferredFilters { get; set; }

        [JsonPropertyName("reports_folder")]
        public string? ReportsFolder { get; set; }
    }

    public partial class Normalization
    {
        [JsonPropertyName("audio")]
        public Audio Audio { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("subtitle")]
        public Subtitle? Subtitle { get; set; }

        [JsonPropertyName("video")]
        public Video Video { get; set; }
    }

    public partial class Audio
    {
        [JsonPropertyName("bitrate_kbps")]
        public long? BitrateKbps { get; set; }

        [JsonPropertyName("buffer_kbps")]
        public long? BufferKbps { get; set; }

        [JsonPropertyName("channels")]
        public long? Channels { get; set; }

        /// <summary>
        /// Source codecs to copy when `mode` is `copy`. Default: aac, ac3, eac3, mp3.
        /// </summary>
        [JsonPropertyName("copy_formats")]
        public List<AudioCopyFormat>? CopyFormats { get; set; }

        /// <summary>
        /// Codec for transcoded items. When `mode` is `copy`, used only for items that are not
        /// copied.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("format")]
        public AudioFormat? Format { get; set; }

        [JsonPropertyName("loudness")]
        public LoudnessClass? Loudness { get; set; }

        /// <summary>
        /// `copy`: copy items with a source codec in `copy_formats`. Transcode all other items.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("mode")]
        public StreamMode? Mode { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("normalize_loudness")]
        public bool? NormalizeLoudness { get; set; }

        [JsonPropertyName("sample_rate_hz")]
        public long? SampleRateHz { get; set; }
    }

    public partial class LoudnessClass
    {
        [JsonPropertyName("integrated_target")]
        public double? IntegratedTarget { get; set; }

        [JsonPropertyName("range_target")]
        public double? RangeTarget { get; set; }

        [JsonPropertyName("true_peak")]
        public double? TruePeak { get; set; }
    }

    public partial class Subtitle
    {
        [JsonPropertyName("fonts_folder")]
        public string? FontsFolder { get; set; }

        [JsonPropertyName("force_style")]
        public string? ForceStyle { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("mode")]
        public SubtitleMode? Mode { get; set; }
    }

    public partial class Video
    {
        [JsonPropertyName("accel")]
        public AccelEnum? Accel { get; set; }

        /// <summary>
        /// Windows only. Unset picks the discrete AMD adapter.
        /// </summary>
        [JsonPropertyName("amf_device")]
        public long? AmfDevice { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("bit_depth")]
        public long? BitDepth { get; set; }

        [JsonPropertyName("bitrate_kbps")]
        public long? BitrateKbps { get; set; }

        [JsonPropertyName("buffer_kbps")]
        public long? BufferKbps { get; set; }

        /// <summary>
        /// Source codecs to copy when `mode` is `copy`. Default: h264, hevc.
        /// </summary>
        [JsonPropertyName("copy_formats")]
        public List<VideoFormat>? CopyFormats { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("deinterlace")]
        public bool? Deinterlace { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("filters")]
        public Filters? Filters { get; set; }

        /// <summary>
        /// Codec for transcoded items. When `mode` is `copy`, this and all other video settings
        /// apply
        /// only to items that are not copied.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("format")]
        public VideoFormat? Format { get; set; }

        /// <summary>
        /// Output frame rate, `N` or `N/D` (e.g. `25`, `30000/1001`).
        /// Frames are dropped or repeated to match it.
        /// In `copy` mode, only items at this rate are copied. Unset keeps the source rate.
        /// </summary>
        [JsonPropertyName("frame_rate")]
        public string? FrameRate { get; set; }

        [JsonPropertyName("height")]
        public long? Height { get; set; }

        /// <summary>
        /// `copy`: copy items with a source codec in `copy_formats`. Transcode all other items, and
        /// items with graphics, burned-in subtitles, still images, Dolby Vision profile 5 or AVI
        /// sources.
        /// </summary>
        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("mode")]
        public StreamMode? Mode { get; set; }

        [JsonIgnore(Condition = JsonIgnoreCondition.WhenWritingNull)]
        [JsonPropertyName("scaling_mode")]
        public ScalingMode? ScalingMode { get; set; }

        /// <summary>
        /// Unset uses `/dev/dri/renderD128`.
        /// </summary>
        [JsonPropertyName("vaapi_device")]
        public string? VaapiDevice { get; set; }

        /// <summary>
        /// Unset lets libva select the driver for `vaapi_device`.
        /// </summary>
        [JsonPropertyName("vaapi_driver")]
        public VaapiDriverEnum? VaapiDriver { get; set; }

        [JsonPropertyName("width")]
        public long? Width { get; set; }
    }

    public partial class Filters
    {
        [JsonPropertyName("bwdif")]
        public BwdifClass? Bwdif { get; set; }

        [JsonPropertyName("bwdif_cuda")]
        public BwdifCudaClass? BwdifCuda { get; set; }

        [JsonPropertyName("deinterlace_qsv")]
        public DeinterlaceQsvClass? DeinterlaceQsv { get; set; }

        [JsonPropertyName("deinterlace_vaapi")]
        public DeinterlaceVaapiClass? DeinterlaceVaapi { get; set; }

        [JsonPropertyName("libplacebo")]
        public LibplaceboClass? Libplacebo { get; set; }

        [JsonPropertyName("tonemap")]
        public TonemapClass? Tonemap { get; set; }

        [JsonPropertyName("tonemap_opencl")]
        public TonemapOpenclClass? TonemapOpencl { get; set; }

        [JsonPropertyName("w3fdif")]
        public W3FdifClass? W3Fdif { get; set; }

        [JsonPropertyName("yadif")]
        public YadifClass? Yadif { get; set; }

        [JsonPropertyName("yadif_cuda")]
        public YadifCudaClass? YadifCuda { get; set; }
    }

    public partial class BwdifClass
    {
        [JsonPropertyName("mode")]
        public string? Mode { get; set; }
    }

    public partial class BwdifCudaClass
    {
        [JsonPropertyName("mode")]
        public string? Mode { get; set; }
    }

    public partial class DeinterlaceQsvClass
    {
        [JsonPropertyName("mode")]
        public string? Mode { get; set; }
    }

    public partial class DeinterlaceVaapiClass
    {
        [JsonPropertyName("mode")]
        public string? Mode { get; set; }
    }

    public partial class LibplaceboClass
    {
        [JsonPropertyName("tonemapping")]
        public string? Tonemapping { get; set; }
    }

    public partial class TonemapClass
    {
        [JsonPropertyName("tonemap")]
        public string? Tonemap { get; set; }
    }

    public partial class TonemapOpenclClass
    {
        [JsonPropertyName("tonemap")]
        public string? Tonemap { get; set; }
    }

    public partial class W3FdifClass
    {
        [JsonPropertyName("mode")]
        public string? Mode { get; set; }
    }

    public partial class YadifClass
    {
        [JsonPropertyName("mode")]
        public string? Mode { get; set; }
    }

    public partial class YadifCudaClass
    {
        [JsonPropertyName("mode")]
        public string? Mode { get; set; }
    }

    public partial class Playout
    {
        [JsonPropertyName("folder")]
        public string Folder { get; set; }

        /// <summary>
        /// RFC3339 formatted date/time, e.g. 2026-04-13T00:24:21.527-05:00
        /// </summary>
        [JsonPropertyName("virtual_start")]
        public string? VirtualStart { get; set; }
    }

    /// <summary>
    /// Limited to codecs that mux correctly into HLS MPEG-TS.
    /// </summary>
    public enum AudioCopyFormat { Aac, Ac3, Eac3, Mp2, Mp3 };

    /// <summary>
    /// Codec for transcoded items. When `mode` is `copy`, used only for items that are not
    /// copied.
    /// </summary>
    public enum AudioFormat { Aac, Ac3 };

    /// <summary>
    /// `copy`: copy items with a source codec in `copy_formats`. Transcode all other items.
    ///
    /// `copy`: copy items with a source codec in `copy_formats`. Transcode all other items, and
    /// items with graphics, burned-in subtitles, still images, Dolby Vision profile 5 or AVI
    /// sources.
    /// </summary>
    public enum StreamMode { Copy, Transcode };

    public enum SubtitleMode { Burn, Convert };

    public enum AccelEnum { Amf, Cuda, Qsv, Rkmpp, Vaapi, Videotoolbox, Vulkan };

    /// <summary>
    /// Codec for transcoded items. When `mode` is `copy`, this and all other video settings
    /// apply
    /// only to items that are not copied.
    /// </summary>
    public enum VideoFormat { H264, Hevc, Mpeg2Video };

    public enum ScalingMode { Crop, ScaleAndPad, Stretch };

    public enum VaapiDriverEnum { I965, Ihd, Radeonsi };

    public partial class ChannelConfig
    {
        public static ChannelConfig FromJson(string json) => JsonSerializer.Deserialize<ChannelConfig>(json, ErsatzTV.Core.Next.Config.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this ChannelConfig self) => JsonSerializer.Serialize(self, ErsatzTV.Core.Next.Config.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
            Converters =
            {
                AudioCopyFormatConverter.Singleton,
                AudioFormatConverter.Singleton,
                StreamModeConverter.Singleton,
                SubtitleModeConverter.Singleton,
                AccelEnumConverter.Singleton,
                VideoFormatConverter.Singleton,
                ScalingModeConverter.Singleton,
                VaapiDriverEnumConverter.Singleton,
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    internal class AudioCopyFormatConverter : JsonConverter<AudioCopyFormat>
    {
        public override bool CanConvert(Type t) => t == typeof(AudioCopyFormat);

        public override AudioCopyFormat Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "aac":
                    return AudioCopyFormat.Aac;
                case "ac3":
                    return AudioCopyFormat.Ac3;
                case "eac3":
                    return AudioCopyFormat.Eac3;
                case "mp2":
                    return AudioCopyFormat.Mp2;
                case "mp3":
                    return AudioCopyFormat.Mp3;
            }
            throw new Exception("Cannot unmarshal type AudioCopyFormat");
        }

        public override void Write(Utf8JsonWriter writer, AudioCopyFormat value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case AudioCopyFormat.Aac:
                    JsonSerializer.Serialize(writer, "aac", options);
                    return;
                case AudioCopyFormat.Ac3:
                    JsonSerializer.Serialize(writer, "ac3", options);
                    return;
                case AudioCopyFormat.Eac3:
                    JsonSerializer.Serialize(writer, "eac3", options);
                    return;
                case AudioCopyFormat.Mp2:
                    JsonSerializer.Serialize(writer, "mp2", options);
                    return;
                case AudioCopyFormat.Mp3:
                    JsonSerializer.Serialize(writer, "mp3", options);
                    return;
            }
            throw new Exception("Cannot marshal type AudioCopyFormat");
        }

        public static readonly AudioCopyFormatConverter Singleton = new AudioCopyFormatConverter();
    }

    internal class AudioFormatConverter : JsonConverter<AudioFormat>
    {
        public override bool CanConvert(Type t) => t == typeof(AudioFormat);

        public override AudioFormat Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "aac":
                    return AudioFormat.Aac;
                case "ac3":
                    return AudioFormat.Ac3;
            }
            throw new Exception("Cannot unmarshal type AudioFormat");
        }

        public override void Write(Utf8JsonWriter writer, AudioFormat value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case AudioFormat.Aac:
                    JsonSerializer.Serialize(writer, "aac", options);
                    return;
                case AudioFormat.Ac3:
                    JsonSerializer.Serialize(writer, "ac3", options);
                    return;
            }
            throw new Exception("Cannot marshal type AudioFormat");
        }

        public static readonly AudioFormatConverter Singleton = new AudioFormatConverter();
    }

    internal class StreamModeConverter : JsonConverter<StreamMode>
    {
        public override bool CanConvert(Type t) => t == typeof(StreamMode);

        public override StreamMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "copy":
                    return StreamMode.Copy;
                case "transcode":
                    return StreamMode.Transcode;
            }
            throw new Exception("Cannot unmarshal type StreamMode");
        }

        public override void Write(Utf8JsonWriter writer, StreamMode value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case StreamMode.Copy:
                    JsonSerializer.Serialize(writer, "copy", options);
                    return;
                case StreamMode.Transcode:
                    JsonSerializer.Serialize(writer, "transcode", options);
                    return;
            }
            throw new Exception("Cannot marshal type StreamMode");
        }

        public static readonly StreamModeConverter Singleton = new StreamModeConverter();
    }

    internal class SubtitleModeConverter : JsonConverter<SubtitleMode>
    {
        public override bool CanConvert(Type t) => t == typeof(SubtitleMode);

        public override SubtitleMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "burn":
                    return SubtitleMode.Burn;
                case "convert":
                    return SubtitleMode.Convert;
            }
            throw new Exception("Cannot unmarshal type SubtitleMode");
        }

        public override void Write(Utf8JsonWriter writer, SubtitleMode value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case SubtitleMode.Burn:
                    JsonSerializer.Serialize(writer, "burn", options);
                    return;
                case SubtitleMode.Convert:
                    JsonSerializer.Serialize(writer, "convert", options);
                    return;
            }
            throw new Exception("Cannot marshal type SubtitleMode");
        }

        public static readonly SubtitleModeConverter Singleton = new SubtitleModeConverter();
    }

    internal class AccelEnumConverter : JsonConverter<AccelEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(AccelEnum);

        public override AccelEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "amf":
                    return AccelEnum.Amf;
                case "cuda":
                    return AccelEnum.Cuda;
                case "qsv":
                    return AccelEnum.Qsv;
                case "rkmpp":
                    return AccelEnum.Rkmpp;
                case "vaapi":
                    return AccelEnum.Vaapi;
                case "videotoolbox":
                    return AccelEnum.Videotoolbox;
                case "vulkan":
                    return AccelEnum.Vulkan;
            }
            throw new Exception("Cannot unmarshal type AccelEnum");
        }

        public override void Write(Utf8JsonWriter writer, AccelEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case AccelEnum.Amf:
                    JsonSerializer.Serialize(writer, "amf", options);
                    return;
                case AccelEnum.Cuda:
                    JsonSerializer.Serialize(writer, "cuda", options);
                    return;
                case AccelEnum.Qsv:
                    JsonSerializer.Serialize(writer, "qsv", options);
                    return;
                case AccelEnum.Rkmpp:
                    JsonSerializer.Serialize(writer, "rkmpp", options);
                    return;
                case AccelEnum.Vaapi:
                    JsonSerializer.Serialize(writer, "vaapi", options);
                    return;
                case AccelEnum.Videotoolbox:
                    JsonSerializer.Serialize(writer, "videotoolbox", options);
                    return;
                case AccelEnum.Vulkan:
                    JsonSerializer.Serialize(writer, "vulkan", options);
                    return;
            }
            throw new Exception("Cannot marshal type AccelEnum");
        }

        public static readonly AccelEnumConverter Singleton = new AccelEnumConverter();
    }

    internal class VideoFormatConverter : JsonConverter<VideoFormat>
    {
        public override bool CanConvert(Type t) => t == typeof(VideoFormat);

        public override VideoFormat Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "h264":
                    return VideoFormat.H264;
                case "hevc":
                    return VideoFormat.Hevc;
                case "mpeg2video":
                    return VideoFormat.Mpeg2Video;
            }
            throw new Exception("Cannot unmarshal type VideoFormat");
        }

        public override void Write(Utf8JsonWriter writer, VideoFormat value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case VideoFormat.H264:
                    JsonSerializer.Serialize(writer, "h264", options);
                    return;
                case VideoFormat.Hevc:
                    JsonSerializer.Serialize(writer, "hevc", options);
                    return;
                case VideoFormat.Mpeg2Video:
                    JsonSerializer.Serialize(writer, "mpeg2video", options);
                    return;
            }
            throw new Exception("Cannot marshal type VideoFormat");
        }

        public static readonly VideoFormatConverter Singleton = new VideoFormatConverter();
    }

    internal class ScalingModeConverter : JsonConverter<ScalingMode>
    {
        public override bool CanConvert(Type t) => t == typeof(ScalingMode);

        public override ScalingMode Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "crop":
                    return ScalingMode.Crop;
                case "scale_and_pad":
                    return ScalingMode.ScaleAndPad;
                case "stretch":
                    return ScalingMode.Stretch;
            }
            throw new Exception("Cannot unmarshal type ScalingMode");
        }

        public override void Write(Utf8JsonWriter writer, ScalingMode value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case ScalingMode.Crop:
                    JsonSerializer.Serialize(writer, "crop", options);
                    return;
                case ScalingMode.ScaleAndPad:
                    JsonSerializer.Serialize(writer, "scale_and_pad", options);
                    return;
                case ScalingMode.Stretch:
                    JsonSerializer.Serialize(writer, "stretch", options);
                    return;
            }
            throw new Exception("Cannot marshal type ScalingMode");
        }

        public static readonly ScalingModeConverter Singleton = new ScalingModeConverter();
    }

    internal class VaapiDriverEnumConverter : JsonConverter<VaapiDriverEnum>
    {
        public override bool CanConvert(Type t) => t == typeof(VaapiDriverEnum);

        public override VaapiDriverEnum Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            switch (value)
            {
                case "i965":
                    return VaapiDriverEnum.I965;
                case "ihd":
                    return VaapiDriverEnum.Ihd;
                case "radeonsi":
                    return VaapiDriverEnum.Radeonsi;
            }
            throw new Exception("Cannot unmarshal type VaapiDriverEnum");
        }

        public override void Write(Utf8JsonWriter writer, VaapiDriverEnum value, JsonSerializerOptions options)
        {
            switch (value)
            {
                case VaapiDriverEnum.I965:
                    JsonSerializer.Serialize(writer, "i965", options);
                    return;
                case VaapiDriverEnum.Ihd:
                    JsonSerializer.Serialize(writer, "ihd", options);
                    return;
                case VaapiDriverEnum.Radeonsi:
                    JsonSerializer.Serialize(writer, "radeonsi", options);
                    return;
            }
            throw new Exception("Cannot marshal type VaapiDriverEnum");
        }

        public static readonly VaapiDriverEnumConverter Singleton = new VaapiDriverEnumConverter();
    }

    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
                this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                var value = reader.GetString();
                return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
                get => _dateTimeStyles;
                set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
                get => _dateTimeFormat ?? string.Empty;
                set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
                get => _culture ?? CultureInfo.CurrentCulture;
                set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
                string text;


                if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                        || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
                {
                        value = value.ToUniversalTime();
                }

                text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

                writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
                string? dateText = reader.GetString();

                if (string.IsNullOrEmpty(dateText) == false)
                {
                        if (!string.IsNullOrEmpty(_dateTimeFormat))
                        {
                                return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                        }
                        else
                        {
                                return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                        }
                }
                else
                {
                        return default(DateTimeOffset);
                }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8602
#pragma warning restore CS8603
