name: Release
on:
  release:
    types: [ published ]
jobs:
  build_and_upload:
    uses: ersatztv/legacy/.github/workflows/artifacts.yml@main
    with:
      tag: ${{ github.event.release.tag_name }}
    secrets:
      apple_developer_certificate_p12_base64: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
      apple_developer_certificate_password: ${{ secrets.APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}
      ac_username: ${{ secrets.AC_USERNAME }}
      ac_password: ${{ secrets.AC_PASSWORD }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
      azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
      azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  build_images:
    uses: ersatztv/legacy/.github/workflows/docker.yml@main
    with:
      base_version: latest
      tag: ${{ github.event.release.tag_name }}
    secrets:
      docker_hub_username: ${{ secrets.DOCKER_HUB_USERNAME }}
      docker_hub_access_token: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
